name: "Terraform Apply for AWS Resource"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init
        working-directory: ${{ github.event.head_commit.message }}

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: ${{ github.event.head_commit.message }}
