# .github/workflows/terraform-plan.yml
name: "Terraform Plan for ${{ parameters.resource_type }}"
on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init -backend=false
        working-directory: ${{ parameters.resource_type }}

      - name: Plan Terraform
        run: terraform plan -input=false -var="region=${{ parameters.region }}" ${{ steps.user-input.output.parameters }}
        working-directory: ${{ parameters.resource_type }}

      - name: Generate Backstage Catalog File
        run: |
          cat <<EOF > catalog-info.yaml
          apiVersion: backstage.io/v1alpha1
          kind: Resource
          metadata:
            name: "${{ parameters.resource_type }}-${{ steps.uuid.output.id }}"
            description: "AWS ${{ parameters.resource_type }} provisioned in ${{ parameters.region }}"
            tags:
              - aws
              - terraform
          spec:
            type: cloud-resource
            owner: team-devops
            system: aws
            provider: terraform
            region: ${{ parameters.region }}
          EOF
        working-directory: ${{ parameters.resource_type }}

      - name: Push Catalog File
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b feature/${{ parameters.resource_type }}-provision-${{ steps.uuid.output.id }}
          git add catalog-info.yaml
          git commit -m "Adding Backstage catalog entry for ${{ parameters.resource_type }}"
          git push origin feature/${{ parameters.resource_type }}-provision-${{ steps.uuid.output.id }}
